### ISSUE TITLE
The pre-trained model cannot be downloaded

### ISSUE THREAD

**Issue by cherish-fere** [moralesq/DeepStrain#10]
I want to try this model on the ACDC dataset, but the link to your pre-trained model is dead, please fix it. Thank you very much!

**Comment by moralesq** [comment]
The trained model is now available through the Harvard Dataverse: https://doi.org/10.7910/DVN/XB6PEZ. 

Please confirm that you can download it and use it.

**Comment by moralesq** [comment]
The download scripts were updated with new data server.

**Comment by moralesq** [comment]
All models and data scripts were updated with working urls.
